# These are all the cops that are disabled in the default configuration.

Style/Copyright:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*_spec.rb"