name: Run tests

on:
  push:
    branches-ignore: [ release ]
  pull_request:
    branches: [ master release ]

jobs:
  build:
    name: Build + Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.147.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: |
        bundle install
        CI=true bundle exec rspec
    # - name: Upload report
    #   run: |
    #     mv ./coverage/coverage.xml cobertura.xml
    #     bash <(curl -Ls https://coverage.codacy.com/get.sh) report
    #   env:
    #     CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
